version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    reviewers:
      - "frc-862/reviewers"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[#3] "
    labels:
      - "thunder"
    milestone: 1